### ISSUE TITLE
Gateway WS client broken in v2.3.0 standalone build (b.mask) + hardcoded protocol v3 blocks OpenClaw >= 2026.6.11

### ISSUE THREAD

**Issue by elvisimtec** [builderz-labs/mission-control#955]
### Environment
- Mission Control `ghcr.io/builderz-labs/mission-control:v2.3.0` (Docker standalone, Traefik + Authentik forward-auth)
- OpenClaw gateway `ghcr.io/openclaw/openclaw:2026.7.1-2` (also reproduced against `2026.8.1`)
- Connection path: MC container → `ws://openclaw-gateway:18789` over a shared Docker network (verified: `healthz` 200, WS upgrade 101, `connect.challenge` received)

### Problem 1 — built-in WS client crash: `TypeError: b.mask is not a function`

MC's server-side gateway stub (`.next/server/chunks/5746.js`, module 25484 in the v2.3.0 standalone build) crashes **when sending any frame**:

```
TypeError: b.mask is not a function
```

The connect frame never reaches the gateway — `chat.send` and `agent` RPCs time out. This reproduces against any WS endpoint, not just OpenClaw (verified E2E with a minimal protocol-3 echo shim). It looks like the bundled `ws` version in the standalone build is missing the `mask` function on the client-side send path (masking is client-mandatory for `ws` ≥ 7 per RFC 6455; typically a broken/partial `ws` bundling or a polyfill clash in the Next standalone output).

### Problem 2 — `GATEWAY_PROTOCOL_VERSION = 3` hardcoded; OpenClaw requires protocol 4 + device identity

`src/lib/openclaw-gateway.ts` line 7:

```ts
const GATEWAY_PROTOCOL_VERSION = 3
```

OpenClaw gateways ≥ `2026.6.11` (including current `2026.8.x`) **require protocol 4** and a **device identity block** in the connect params:

```json
"params": {
  "minProtocol": 4, "maxProtocol": 4,
  "client": { "id": "...", "version": "...", "platform": "..." },
  "role": "operator", "scopes": [...],
  "auth": { "token": "..." },
  "device": {
    "id": "<device fingerprint>",
    "publicKey": "…",
    "signature": "…",
    "signedAt": 1737264000000
  }
}
```

A live test against OpenClaw `2026.7.1-2` shows the handshake stage progression: `PROTOCOL_MISMATCH` → (bumping to 4) → `DEVICE_IDENTITY_REQUIRED`. Bumping the constant alone is not sufficient — the v4 connect schema needs a generated device keypair + signature over the challenge (`ts` from `connect.challenge` used as `signedAt`). OpenClaw also supports trusted-proxy auto-approval of paired devices, which fits MC's forward-auth deployment model.

### Reproduction

1. Deploy MC v2.3.0, set `OPENCLAW_GATEWAY_HOST/PORT` to any reachable WS endpoint.
2. MC logs: `TypeError: b.mask is not a function` on first frame send (see above).
3. With the WS client fixed, MC sends `minProtocol: 3, maxProtocol: 3` → OpenClaw rejects with `PROTOCOL_MISMATCH`.
4. Upgrading the constant to 4 → `DEVICE_IDENTITY_REQUIRED`.

### Request

1. **Fix the standalone-build `ws` client masking** (blocks *all* server-side gateway connectivity).
2. **Adopt gateway protocol 4 + device identity/pairing** (so MC works with OpenClaw ≥ 2026.6.11; a version constant/env override plus a per-install device key would be enough).

Related: #701 (protocol mismatch report), #104 (unmerged earlier device-auth handshake alignment). Happy to test a patch against our deployment.
